version: '3.8'
services:
  mongo-db:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/
    ports:
    - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: Hackathon